# 1) Numpy

In [3]:
import numpy as np
import time 

## -> performance of numpy array is faster

In [4]:
size = 1_000_000

# python list

py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} s")


# numpy arrays
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr ** 2
end = time.time()
print(f"python list time = {end-start} s")

python list time = 0.12368011474609375 s
python list time = 0.021683692932128906 s


## -> memory

In [6]:
import sys

print(f"python list size : {sys.getsizeof(py_list) * len(py_list)} bytes")

print(f"numpy array size : {np_arr.nbytes} bytes")


python list size : 8000056000000 bytes
numpy array size : 8000000 bytes


# -> creating arrays from list

In [8]:
# 1d array
arr = np.array([1,2,3,4])
print(arr,type(arr),arr.dtype,arr.shape)

[1 2 3 4] <class 'numpy.ndarray'> int64 (4,)


In [10]:
# 2d array
arr2 = np.array([[1,2,3,4],[5,6,7,8],[5,3,7,4]])
print(arr2,type(arr2),arr2.dtype,arr2.shape)

[[1 2 3 4]
 [5 6 7 8]
 [5 3 7 4]] <class 'numpy.ndarray'> int64 (3, 4)


## -> built in methods 

In [11]:
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
arr = np.ones((2,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
arr = np.full((2,4),100)
print(arr)

[[100 100 100 100]
 [100 100 100 100]]


In [15]:
arr = np.eye((3))
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
arr = np.arange(2,10,2)
print(arr)

[2 4 6 8]


In [21]:
arr = np.linspace(2,100,5)
print(arr)

[  2.   26.5  51.   75.5 100. ]


In [24]:
# type convertion
arr = np.array([[2, 3], [2, 4]], dtype="int64")
print(arr)

[[2 3]
 [2 4]]


## -> Properties of arrays

In [27]:
# reshaping arrays

arr = np.array([1,2,3,4,5,6])
reshape = arr.reshape((3,2))
print(reshape,reshape.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [29]:
# flatten -> 2d to 1d conversion

arr = np.array([[2,3,4],[5,6,7]])
flat = arr.flatten()
print(flat)

[2 3 4 5 6 7]


In [30]:
# indexing

arr = np.array([[2,3,4],[5,6,7]])
print(arr[0][2])

4


In [32]:
# fancy indexing -> access multiple values

arr = np.array([4,3,5,6,3,2,7,2,5])

idx = [3,5,7]

print(arr[idx])

[6 2 2]


In [34]:
 # boolean indexing

arr = np.array([4,3,5,6,3,2,7,2,5])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])
print(arr[arr > 3])

[4 6 2 2]
[3 5 3 7 5]
[4 5 6 7 5]


In [37]:
# slice

arr = np.array([4,3,5,6,3,2,7,2,5])
print(arr[0:8:2])

[4 5 3 7]


# -> Data Types

In [40]:
import numpy as np

# integer array
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1.0, 2.0, 3.0])
arr3 = np.array(["hello", "world", "prime", "ai/ml"])

print(arr.dtype)   # int64
print(arr2.dtype)  # float64
print(arr3.dtype)  # <U (string / unicode)

# Complex Numbers
arr1 = np.array([2 + 3j])
arr2 = np.array([5 + 8j])

print(arr1, arr1.dtype)  # dtype = complex128
print(arr1 + arr2)       # addition of complex numbers
print(arr2 - arr1)       # subtraction of complex numbers

# Objects
arr4 = np.array(["hello", {1, 2, 3}, 3.14], dtype=object)
print(arr4, arr4.dtype)  # dtype = object


int64
float64
<U5
[2.+3.j] complex128
[7.+11.j]
[3.+5.j]
['hello' {1, 2, 3} 3.14] object


# -> 2d array axes 

In [44]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

print(np.sum(arr))

print(np.sum(arr , axis=0))

print(np.sum(arr , axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]


# -> 3d array axes

In [48]:
arr = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,1],[2,3]]])
print(arr,arr.shape)

# indexing

print(arr[1][1][1])

# slicing

print(arr[:,0,:])

# replacing

arr[:,0,:] = 98
print(arr)

[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [9 1]
  [2 3]]] (2, 3, 2)
1
[[1 2]
 [7 8]]
[[[98 98]
  [ 3  4]
  [ 5  6]]

 [[98 98]
  [ 9  1]
  [ 2  3]]]


# -> vectorization and broadcasting

In [51]:
# vectorization -> ek saath operation apply in whole array

arr = np.array([1,2,3,4])
print(arr ** 2)
print(arr + 2)

[ 1  4  9 16]
[3 4 5 6]


In [54]:
# broadcasting

print(arr+5)

arr1 = np.array([1,2,3,4])
arr2 = np.array([[11,22,33,44],[1,2,3,4]])

print(arr1 + arr2)


[6 7 8 9]
[[12 24 36 48]
 [ 2  4  6  8]]


In [55]:
# normalization

arr = np.array([[1,2],[3,4]])
mean = np.mean(arr)
s_dev = np.std(arr)

n_arr = (arr-mean)/s_dev
print(n_arr)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


# -> mathematical functions

In [71]:
# aggregation functions

arr = np.array([1,2.4,3,4,1,2])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.var(arr))
print(np.std(arr))

# power  function

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,4))

# log functions

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

# rounding

print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

# extras

print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

13.4
57.599999999999994
1.0
4.0
0
3
2.2333333333333334
2.2
1.1388888888888886
1.0671873729054746
[ 1.    5.76  9.   16.    1.    4.  ]
[1.         1.54919334 1.73205081 2.         1.         1.41421356]
[  1.      33.1776  81.     256.       1.      16.    ]
[0.         0.87546874 1.09861229 1.38629436 0.         0.69314718]
[0.         0.38021124 0.47712125 0.60205999 0.         0.30103   ]
[0.         1.26303441 1.5849625  2.         0.         1.        ]
[ 2.71828183 11.02317638 20.08553692 54.59815003  2.71828183  7.3890561 ]
3.0
4.0
3.0
3.0
[1.  2.  2.4 3.  4. ]
[1.  1.  2.  2.4 3.  4. ]
[1.  2.4 3.  4.  1.  2. ]
